[package]
name = "expectation_plugin"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]
description = "Expectation Tests Plugin"
license = "MIT/Apache-2.0"

[lib]
name = "expectation_plugin"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "0.6.8"

[dependencies.syn]
version = "0.14.9"
features = ["full"]
