[package]
name = "expectation-shared"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]
description = "Expectation Tests Shared Code (Dont depend on this package, I don't know why I have to publish it)"
license = "MIT/Apache-2.0"

[dependencies]
serde = "1.*.*"
serde_derive = "1.*.*"
walkdir = "2.2.0"
